# Load calibration dataset

In [1]:
_DATA = load("-ascii", "EC1-Measurements.txt");
size(_DATA)

ans =

        1   750000



In [2]:
DATA = reshape(_DATA, 3, [])';
[N, _] = size(DATA)

N =  250000
_ =  3


In [3]:
m_true = [11.7 140.2 33.5]
m_data = mean(DATA) % make sure DATA is not garbage, being loaded this way

m_true =

    11.700   140.200    33.500

m_data =

    11.707   140.207    33.502



# Covariance matrix

In [4]:
c_theory = [4 2 -1; 2 4 2; -1 2 4]

% sample error covariance matrix 
c_data = zeros(3);
for i=1:N
  c_data += (DATA(i,:) - m_true)'*(DATA(i,:) - m_true);
end
c_data ./= N-1

c_theory =

   4   2  -1
   2   4   2
  -1   2   4

c_data =

   3.98475   1.98899  -0.99789
   1.98899   3.99004   2.00644
  -0.99789   2.00644   4.00510



The theoretical covariance is **NOT** conservative because the inequality $C_\text{theory} \ge C_\text{data}$ does not hold.
In fact $(C_\text{theory} - C_\text{data})$ is not PSD, but has one negative eigen value.

In [5]:
eig(c_theory - c_data)

ans =

  -0.0076832
   0.0027852
   0.0250044

